repos:
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        files: "\\.(py)$"
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        files: "\\.(py)$"
        language_version: python3.8
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: "\\.(py)$"
        name: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'
    hooks:
      - id: mypy
        files: src
        additional_dependencies: [
          PyQt5-stubs==5.15.2.0, 
          numpy==1.21.2, 
          python-magic==0.4.24
        ]
