repos:
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        files: "\\.(py)$"
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        files: "\\.(py)$"
        language_version: python3.8
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: "\\.(py)$"
        name: isort (python)
