# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'snooker-ball-tracker.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1269, 877)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setAnimated(False)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.central_widget.sizePolicy().hasHeightForWidth())
        self.central_widget.setSizePolicy(sizePolicy)
        self.central_widget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.central_widget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.central_widget.setObjectName("central_widget")
        self.central_widget_layout = QtWidgets.QGridLayout(self.central_widget)
        self.central_widget_layout.setContentsMargins(15, 15, 15, 15)
        self.central_widget_layout.setSpacing(15)
        self.central_widget_layout.setObjectName("central_widget_layout")
        self.settings_groupbox = QtWidgets.QGroupBox(self.central_widget)
        self.settings_groupbox.setObjectName("settings_groupbox")
        self.settings_groupbox_layout = QtWidgets.QHBoxLayout(self.settings_groupbox)
        self.settings_groupbox_layout.setContentsMargins(15, 15, 15, 15)
        self.settings_groupbox_layout.setObjectName("settings_groupbox_layout")
        self.settings_tabs = QtWidgets.QTabWidget(self.settings_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_tabs.sizePolicy().hasHeightForWidth())
        self.settings_tabs.setSizePolicy(sizePolicy)
        self.settings_tabs.setMinimumSize(QtCore.QSize(0, 0))
        self.settings_tabs.setMaximumSize(QtCore.QSize(589, 16777215))
        self.settings_tabs.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.settings_tabs.setMovable(False)
        self.settings_tabs.setObjectName("settings_tabs")
        self.colourDetection_tab = QtWidgets.QWidget()
        self.colourDetection_tab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.colourDetection_tab.setObjectName("colourDetection_tab")
        self.colourDetection_tab_layout = QtWidgets.QGridLayout(self.colourDetection_tab)
        self.colourDetection_tab_layout.setHorizontalSpacing(15)
        self.colourDetection_tab_layout.setObjectName("colourDetection_tab_layout")
        self.detectColour_horz_line1 = QtWidgets.QFrame(self.colourDetection_tab)
        self.detectColour_horz_line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.detectColour_horz_line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.detectColour_horz_line1.setObjectName("detectColour_horz_line1")
        self.colourDetection_tab_layout.addWidget(self.detectColour_horz_line1, 0, 0, 1, 7)
        self.detectColour_label = QtWidgets.QLabel(self.colourDetection_tab)
        self.detectColour_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.detectColour_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.detectColour_label.setAlignment(QtCore.Qt.AlignCenter)
        self.detectColour_label.setObjectName("detectColour_label")
        self.colourDetection_tab_layout.addWidget(self.detectColour_label, 1, 0, 1, 1)
        self.detectColour_combobox = QtWidgets.QComboBox(self.colourDetection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detectColour_combobox.sizePolicy().hasHeightForWidth())
        self.detectColour_combobox.setSizePolicy(sizePolicy)
        self.detectColour_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.detectColour_combobox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.detectColour_combobox.setFrame(True)
        self.detectColour_combobox.setObjectName("detectColour_combobox")
        self.colourDetection_tab_layout.addWidget(self.detectColour_combobox, 1, 1, 1, 2)
        self.showMask_label = QtWidgets.QLabel(self.colourDetection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showMask_label.sizePolicy().hasHeightForWidth())
        self.showMask_label.setSizePolicy(sizePolicy)
        self.showMask_label.setObjectName("showMask_label")
        self.colourDetection_tab_layout.addWidget(self.showMask_label, 1, 3, 1, 1)
        self.showMask_yradio = QtWidgets.QRadioButton(self.colourDetection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showMask_yradio.sizePolicy().hasHeightForWidth())
        self.showMask_yradio.setSizePolicy(sizePolicy)
        self.showMask_yradio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.showMask_yradio.setObjectName("showMask_yradio")
        self.colourDetection_tab_layout.addWidget(self.showMask_yradio, 1, 4, 1, 1)
        self.showMask_nradio = QtWidgets.QRadioButton(self.colourDetection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showMask_nradio.sizePolicy().hasHeightForWidth())
        self.showMask_nradio.setSizePolicy(sizePolicy)
        self.showMask_nradio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.showMask_nradio.setObjectName("showMask_nradio")
        self.colourDetection_tab_layout.addWidget(self.showMask_nradio, 1, 5, 1, 1)
        self.reset_btn = QtWidgets.QPushButton(self.colourDetection_tab)
        self.reset_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.reset_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.reset_btn.setAutoFillBackground(False)
        self.reset_btn.setObjectName("reset_btn")
        self.colourDetection_tab_layout.addWidget(self.reset_btn, 1, 6, 1, 1)
        self.detectColour_horz_line2 = QtWidgets.QFrame(self.colourDetection_tab)
        self.detectColour_horz_line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.detectColour_horz_line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.detectColour_horz_line2.setObjectName("detectColour_horz_line2")
        self.colourDetection_tab_layout.addWidget(self.detectColour_horz_line2, 2, 0, 1, 7)
        self.lRange_label = QtWidgets.QLabel(self.colourDetection_tab)
        self.lRange_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lRange_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lRange_label.setAlignment(QtCore.Qt.AlignCenter)
        self.lRange_label.setObjectName("lRange_label")
        self.colourDetection_tab_layout.addWidget(self.lRange_label, 3, 2, 1, 2)
        self.uRange_label = QtWidgets.QLabel(self.colourDetection_tab)
        self.uRange_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.uRange_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.uRange_label.setAlignment(QtCore.Qt.AlignCenter)
        self.uRange_label.setObjectName("uRange_label")
        self.colourDetection_tab_layout.addWidget(self.uRange_label, 3, 5, 1, 2)
        self.hue_label = QtWidgets.QLabel(self.colourDetection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hue_label.sizePolicy().hasHeightForWidth())
        self.hue_label.setSizePolicy(sizePolicy)
        self.hue_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hue_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hue_label.setObjectName("hue_label")
        self.colourDetection_tab_layout.addWidget(self.hue_label, 4, 0, 1, 1)
        self.lHue_label = QtWidgets.QLabel(self.colourDetection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lHue_label.sizePolicy().hasHeightForWidth())
        self.lHue_label.setSizePolicy(sizePolicy)
        self.lHue_label.setMinimumSize(QtCore.QSize(20, 0))
        self.lHue_label.setAlignment(QtCore.Qt.AlignCenter)
        self.lHue_label.setObjectName("lHue_label")
        self.colourDetection_tab_layout.addWidget(self.lHue_label, 4, 1, 1, 1)
        self.lHue_slider = QtWidgets.QSlider(self.colourDetection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lHue_slider.sizePolicy().hasHeightForWidth())
        self.lHue_slider.setSizePolicy(sizePolicy)
        self.lHue_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lHue_slider.setMaximum(255)
        self.lHue_slider.setProperty("value", 0)
        self.lHue_slider.setSliderPosition(0)
        self.lHue_slider.setOrientation(QtCore.Qt.Horizontal)
        self.lHue_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.lHue_slider.setObjectName("lHue_slider")
        self.colourDetection_tab_layout.addWidget(self.lHue_slider, 4, 2, 1, 2)
        self.uHue_label = QtWidgets.QLabel(self.colourDetection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uHue_label.sizePolicy().hasHeightForWidth())
        self.uHue_label.setSizePolicy(sizePolicy)
        self.uHue_label.setMinimumSize(QtCore.QSize(0, 0))
        self.uHue_label.setAlignment(QtCore.Qt.AlignCenter)
        self.uHue_label.setObjectName("uHue_label")
        self.colourDetection_tab_layout.addWidget(self.uHue_label, 4, 4, 1, 1)
        self.uHue_slider = QtWidgets.QSlider(self.colourDetection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uHue_slider.sizePolicy().hasHeightForWidth())
        self.uHue_slider.setSizePolicy(sizePolicy)
        self.uHue_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uHue_slider.setMaximum(255)
        self.uHue_slider.setProperty("value", 0)
        self.uHue_slider.setSliderPosition(0)
        self.uHue_slider.setOrientation(QtCore.Qt.Horizontal)
        self.uHue_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.uHue_slider.setObjectName("uHue_slider")
        self.colourDetection_tab_layout.addWidget(self.uHue_slider, 4, 5, 1, 2)
        self.sat_label = QtWidgets.QLabel(self.colourDetection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sat_label.sizePolicy().hasHeightForWidth())
        self.sat_label.setSizePolicy(sizePolicy)
        self.sat_label.setMinimumSize(QtCore.QSize(0, 0))
        self.sat_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sat_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sat_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sat_label.setObjectName("sat_label")
        self.colourDetection_tab_layout.addWidget(self.sat_label, 5, 0, 1, 1)
        self.lSat_label = QtWidgets.QLabel(self.colourDetection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lSat_label.sizePolicy().hasHeightForWidth())
        self.lSat_label.setSizePolicy(sizePolicy)
        self.lSat_label.setMinimumSize(QtCore.QSize(20, 0))
        self.lSat_label.setAlignment(QtCore.Qt.AlignCenter)
        self.lSat_label.setObjectName("lSat_label")
        self.colourDetection_tab_layout.addWidget(self.lSat_label, 5, 1, 1, 1)
        self.lSat_slider = QtWidgets.QSlider(self.colourDetection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lSat_slider.sizePolicy().hasHeightForWidth())
        self.lSat_slider.setSizePolicy(sizePolicy)
        self.lSat_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lSat_slider.setMaximum(255)
        self.lSat_slider.setProperty("value", 0)
        self.lSat_slider.setSliderPosition(0)
        self.lSat_slider.setOrientation(QtCore.Qt.Horizontal)
        self.lSat_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.lSat_slider.setObjectName("lSat_slider")
        self.colourDetection_tab_layout.addWidget(self.lSat_slider, 5, 2, 1, 2)
        self.uSat_label = QtWidgets.QLabel(self.colourDetection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uSat_label.sizePolicy().hasHeightForWidth())
        self.uSat_label.setSizePolicy(sizePolicy)
        self.uSat_label.setMinimumSize(QtCore.QSize(20, 0))
        self.uSat_label.setAlignment(QtCore.Qt.AlignCenter)
        self.uSat_label.setObjectName("uSat_label")
        self.colourDetection_tab_layout.addWidget(self.uSat_label, 5, 4, 1, 1)
        self.uSat_slider = QtWidgets.QSlider(self.colourDetection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uSat_slider.sizePolicy().hasHeightForWidth())
        self.uSat_slider.setSizePolicy(sizePolicy)
        self.uSat_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uSat_slider.setMaximum(255)
        self.uSat_slider.setProperty("value", 0)
        self.uSat_slider.setSliderPosition(0)
        self.uSat_slider.setOrientation(QtCore.Qt.Horizontal)
        self.uSat_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.uSat_slider.setObjectName("uSat_slider")
        self.colourDetection_tab_layout.addWidget(self.uSat_slider, 5, 5, 1, 2)
        self.val_label = QtWidgets.QLabel(self.colourDetection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.val_label.sizePolicy().hasHeightForWidth())
        self.val_label.setSizePolicy(sizePolicy)
        self.val_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.val_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.val_label.setObjectName("val_label")
        self.colourDetection_tab_layout.addWidget(self.val_label, 6, 0, 1, 1)
        self.lVal_label = QtWidgets.QLabel(self.colourDetection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lVal_label.sizePolicy().hasHeightForWidth())
        self.lVal_label.setSizePolicy(sizePolicy)
        self.lVal_label.setMinimumSize(QtCore.QSize(20, 0))
        self.lVal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.lVal_label.setObjectName("lVal_label")
        self.colourDetection_tab_layout.addWidget(self.lVal_label, 6, 1, 1, 1)
        self.lval_slider = QtWidgets.QSlider(self.colourDetection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lval_slider.sizePolicy().hasHeightForWidth())
        self.lval_slider.setSizePolicy(sizePolicy)
        self.lval_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lval_slider.setMaximum(255)
        self.lval_slider.setProperty("value", 0)
        self.lval_slider.setSliderPosition(0)
        self.lval_slider.setOrientation(QtCore.Qt.Horizontal)
        self.lval_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.lval_slider.setObjectName("lval_slider")
        self.colourDetection_tab_layout.addWidget(self.lval_slider, 6, 2, 1, 2)
        self.uVal_label = QtWidgets.QLabel(self.colourDetection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uVal_label.sizePolicy().hasHeightForWidth())
        self.uVal_label.setSizePolicy(sizePolicy)
        self.uVal_label.setMinimumSize(QtCore.QSize(20, 0))
        self.uVal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.uVal_label.setObjectName("uVal_label")
        self.colourDetection_tab_layout.addWidget(self.uVal_label, 6, 4, 1, 1)
        self.rVal_slider = QtWidgets.QSlider(self.colourDetection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rVal_slider.sizePolicy().hasHeightForWidth())
        self.rVal_slider.setSizePolicy(sizePolicy)
        self.rVal_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rVal_slider.setMaximum(255)
        self.rVal_slider.setProperty("value", 0)
        self.rVal_slider.setSliderPosition(0)
        self.rVal_slider.setOrientation(QtCore.Qt.Horizontal)
        self.rVal_slider.setInvertedControls(False)
        self.rVal_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.rVal_slider.setObjectName("rVal_slider")
        self.colourDetection_tab_layout.addWidget(self.rVal_slider, 6, 5, 1, 2)
        self.settings_tabs.addTab(self.colourDetection_tab, "")
        self.ballDetection_tab = QtWidgets.QWidget()
        self.ballDetection_tab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ballDetection_tab.setObjectName("ballDetection_tab")
        self.ballDetection_tab_layout = QtWidgets.QGridLayout(self.ballDetection_tab)
        self.ballDetection_tab_layout.setObjectName("ballDetection_tab_layout")
        self.convexity_groupbox = QtWidgets.QGroupBox(self.ballDetection_tab)
        self.convexity_groupbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.convexity_groupbox.setObjectName("convexity_groupbox")
        self.convexity_groupbox_layout = QtWidgets.QGridLayout(self.convexity_groupbox)
        self.convexity_groupbox_layout.setObjectName("convexity_groupbox_layout")
        self.convexity_filterBy_label = QtWidgets.QLabel(self.convexity_groupbox)
        self.convexity_filterBy_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.convexity_filterBy_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.convexity_filterBy_label.setAlignment(QtCore.Qt.AlignCenter)
        self.convexity_filterBy_label.setObjectName("convexity_filterBy_label")
        self.convexity_groupbox_layout.addWidget(self.convexity_filterBy_label, 0, 0, 1, 1)
        self.convexity_filterBy_yradio = QtWidgets.QRadioButton(self.convexity_groupbox)
        self.convexity_filterBy_yradio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.convexity_filterBy_yradio.setObjectName("convexity_filterBy_yradio")
        self.convexity_groupbox_layout.addWidget(self.convexity_filterBy_yradio, 0, 1, 1, 1)
        self.convexity_filterBy_nradio = QtWidgets.QRadioButton(self.convexity_groupbox)
        self.convexity_filterBy_nradio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.convexity_filterBy_nradio.setObjectName("convexity_filterBy_nradio")
        self.convexity_groupbox_layout.addWidget(self.convexity_filterBy_nradio, 0, 2, 1, 1)
        self.convexity_minVal_label = QtWidgets.QLabel(self.convexity_groupbox)
        self.convexity_minVal_label.setMaximumSize(QtCore.QSize(300, 16777215))
        self.convexity_minVal_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.convexity_minVal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.convexity_minVal_label.setObjectName("convexity_minVal_label")
        self.convexity_groupbox_layout.addWidget(self.convexity_minVal_label, 1, 0, 1, 1)
        self.convexity_minVal = QtWidgets.QLabel(self.convexity_groupbox)
        self.convexity_minVal.setMaximumSize(QtCore.QSize(100, 16777215))
        self.convexity_minVal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.convexity_minVal.setAlignment(QtCore.Qt.AlignCenter)
        self.convexity_minVal.setObjectName("convexity_minVal")
        self.convexity_groupbox_layout.addWidget(self.convexity_minVal, 1, 1, 1, 1)
        self.convexity_minVal_slider = QtWidgets.QSlider(self.convexity_groupbox)
        self.convexity_minVal_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.convexity_minVal_slider.setOrientation(QtCore.Qt.Horizontal)
        self.convexity_minVal_slider.setObjectName("convexity_minVal_slider")
        self.convexity_groupbox_layout.addWidget(self.convexity_minVal_slider, 1, 2, 1, 1)
        self.convexity_maxVal_label = QtWidgets.QLabel(self.convexity_groupbox)
        self.convexity_maxVal_label.setMaximumSize(QtCore.QSize(300, 16777215))
        self.convexity_maxVal_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.convexity_maxVal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.convexity_maxVal_label.setObjectName("convexity_maxVal_label")
        self.convexity_groupbox_layout.addWidget(self.convexity_maxVal_label, 2, 0, 1, 1)
        self.convexity_maxVal = QtWidgets.QLabel(self.convexity_groupbox)
        self.convexity_maxVal.setMaximumSize(QtCore.QSize(100, 16777215))
        self.convexity_maxVal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.convexity_maxVal.setAlignment(QtCore.Qt.AlignCenter)
        self.convexity_maxVal.setObjectName("convexity_maxVal")
        self.convexity_groupbox_layout.addWidget(self.convexity_maxVal, 2, 1, 1, 1)
        self.convexity_maxVal_slider = QtWidgets.QSlider(self.convexity_groupbox)
        self.convexity_maxVal_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.convexity_maxVal_slider.setOrientation(QtCore.Qt.Horizontal)
        self.convexity_maxVal_slider.setObjectName("convexity_maxVal_slider")
        self.convexity_groupbox_layout.addWidget(self.convexity_maxVal_slider, 2, 2, 1, 1)
        self.convexity_reset_btn = QtWidgets.QPushButton(self.convexity_groupbox)
        self.convexity_reset_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.convexity_reset_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.convexity_reset_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.convexity_reset_btn.setAutoFillBackground(False)
        self.convexity_reset_btn.setCheckable(False)
        self.convexity_reset_btn.setObjectName("convexity_reset_btn")
        self.convexity_groupbox_layout.addWidget(self.convexity_reset_btn, 3, 2, 1, 1)
        self.ballDetection_tab_layout.addWidget(self.convexity_groupbox, 0, 0, 1, 1)
        self.inertia_groupbox = QtWidgets.QGroupBox(self.ballDetection_tab)
        self.inertia_groupbox.setObjectName("inertia_groupbox")
        self.inertia_groupbox_layout = QtWidgets.QGridLayout(self.inertia_groupbox)
        self.inertia_groupbox_layout.setObjectName("inertia_groupbox_layout")
        self.inertia_filterBy_label = QtWidgets.QLabel(self.inertia_groupbox)
        self.inertia_filterBy_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.inertia_filterBy_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inertia_filterBy_label.setAlignment(QtCore.Qt.AlignCenter)
        self.inertia_filterBy_label.setObjectName("inertia_filterBy_label")
        self.inertia_groupbox_layout.addWidget(self.inertia_filterBy_label, 0, 0, 1, 1)
        self.inertia_filterBy_yradio = QtWidgets.QRadioButton(self.inertia_groupbox)
        self.inertia_filterBy_yradio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.inertia_filterBy_yradio.setObjectName("inertia_filterBy_yradio")
        self.inertia_groupbox_layout.addWidget(self.inertia_filterBy_yradio, 0, 1, 1, 1)
        self.inertia_filterBy_nradio = QtWidgets.QRadioButton(self.inertia_groupbox)
        self.inertia_filterBy_nradio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.inertia_filterBy_nradio.setObjectName("inertia_filterBy_nradio")
        self.inertia_groupbox_layout.addWidget(self.inertia_filterBy_nradio, 0, 2, 1, 1)
        self.inertia_minVal_label = QtWidgets.QLabel(self.inertia_groupbox)
        self.inertia_minVal_label.setMaximumSize(QtCore.QSize(300, 16777215))
        self.inertia_minVal_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inertia_minVal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.inertia_minVal_label.setObjectName("inertia_minVal_label")
        self.inertia_groupbox_layout.addWidget(self.inertia_minVal_label, 1, 0, 1, 1)
        self.inertia_minVal = QtWidgets.QLabel(self.inertia_groupbox)
        self.inertia_minVal.setMaximumSize(QtCore.QSize(100, 16777215))
        self.inertia_minVal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inertia_minVal.setAlignment(QtCore.Qt.AlignCenter)
        self.inertia_minVal.setObjectName("inertia_minVal")
        self.inertia_groupbox_layout.addWidget(self.inertia_minVal, 1, 1, 1, 1)
        self.inertia_minVal_slider = QtWidgets.QSlider(self.inertia_groupbox)
        self.inertia_minVal_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.inertia_minVal_slider.setOrientation(QtCore.Qt.Horizontal)
        self.inertia_minVal_slider.setObjectName("inertia_minVal_slider")
        self.inertia_groupbox_layout.addWidget(self.inertia_minVal_slider, 1, 2, 1, 1)
        self.inertia_maxVal_label = QtWidgets.QLabel(self.inertia_groupbox)
        self.inertia_maxVal_label.setMaximumSize(QtCore.QSize(300, 16777215))
        self.inertia_maxVal_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inertia_maxVal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.inertia_maxVal_label.setObjectName("inertia_maxVal_label")
        self.inertia_groupbox_layout.addWidget(self.inertia_maxVal_label, 2, 0, 1, 1)
        self.inertia_maxVal = QtWidgets.QLabel(self.inertia_groupbox)
        self.inertia_maxVal.setMaximumSize(QtCore.QSize(100, 16777215))
        self.inertia_maxVal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inertia_maxVal.setAlignment(QtCore.Qt.AlignCenter)
        self.inertia_maxVal.setObjectName("inertia_maxVal")
        self.inertia_groupbox_layout.addWidget(self.inertia_maxVal, 2, 1, 1, 1)
        self.inertia_maxVal_slider = QtWidgets.QSlider(self.inertia_groupbox)
        self.inertia_maxVal_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.inertia_maxVal_slider.setOrientation(QtCore.Qt.Horizontal)
        self.inertia_maxVal_slider.setObjectName("inertia_maxVal_slider")
        self.inertia_groupbox_layout.addWidget(self.inertia_maxVal_slider, 2, 2, 1, 1)
        self.inertia_reset_btn = QtWidgets.QPushButton(self.inertia_groupbox)
        self.inertia_reset_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.inertia_reset_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.inertia_reset_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inertia_reset_btn.setAutoFillBackground(False)
        self.inertia_reset_btn.setCheckable(False)
        self.inertia_reset_btn.setObjectName("inertia_reset_btn")
        self.inertia_groupbox_layout.addWidget(self.inertia_reset_btn, 3, 2, 1, 1)
        self.ballDetection_tab_layout.addWidget(self.inertia_groupbox, 0, 1, 1, 1)
        self.circularity_groupbox = QtWidgets.QGroupBox(self.ballDetection_tab)
        self.circularity_groupbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.circularity_groupbox.setObjectName("circularity_groupbox")
        self.cicularity_groupbox_layout = QtWidgets.QGridLayout(self.circularity_groupbox)
        self.cicularity_groupbox_layout.setObjectName("cicularity_groupbox_layout")
        self.circular_filterBy_label = QtWidgets.QLabel(self.circularity_groupbox)
        self.circular_filterBy_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.circular_filterBy_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.circular_filterBy_label.setAlignment(QtCore.Qt.AlignCenter)
        self.circular_filterBy_label.setObjectName("circular_filterBy_label")
        self.cicularity_groupbox_layout.addWidget(self.circular_filterBy_label, 0, 0, 1, 1)
        self.circular_filterBy_yradio = QtWidgets.QRadioButton(self.circularity_groupbox)
        self.circular_filterBy_yradio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.circular_filterBy_yradio.setObjectName("circular_filterBy_yradio")
        self.cicularity_groupbox_layout.addWidget(self.circular_filterBy_yradio, 0, 1, 1, 1)
        self.circular_filterBy_nradio = QtWidgets.QRadioButton(self.circularity_groupbox)
        self.circular_filterBy_nradio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.circular_filterBy_nradio.setObjectName("circular_filterBy_nradio")
        self.cicularity_groupbox_layout.addWidget(self.circular_filterBy_nradio, 0, 2, 1, 1)
        self.circular_minVal_label = QtWidgets.QLabel(self.circularity_groupbox)
        self.circular_minVal_label.setMaximumSize(QtCore.QSize(300, 16777215))
        self.circular_minVal_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.circular_minVal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.circular_minVal_label.setObjectName("circular_minVal_label")
        self.cicularity_groupbox_layout.addWidget(self.circular_minVal_label, 1, 0, 1, 1)
        self.circular_minVal = QtWidgets.QLabel(self.circularity_groupbox)
        self.circular_minVal.setMaximumSize(QtCore.QSize(100, 16777215))
        self.circular_minVal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.circular_minVal.setAlignment(QtCore.Qt.AlignCenter)
        self.circular_minVal.setObjectName("circular_minVal")
        self.cicularity_groupbox_layout.addWidget(self.circular_minVal, 1, 1, 1, 1)
        self.circular_minVal_slider = QtWidgets.QSlider(self.circularity_groupbox)
        self.circular_minVal_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.circular_minVal_slider.setOrientation(QtCore.Qt.Horizontal)
        self.circular_minVal_slider.setObjectName("circular_minVal_slider")
        self.cicularity_groupbox_layout.addWidget(self.circular_minVal_slider, 1, 2, 1, 1)
        self.circular_maxVal_label = QtWidgets.QLabel(self.circularity_groupbox)
        self.circular_maxVal_label.setMaximumSize(QtCore.QSize(300, 16777215))
        self.circular_maxVal_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.circular_maxVal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.circular_maxVal_label.setObjectName("circular_maxVal_label")
        self.cicularity_groupbox_layout.addWidget(self.circular_maxVal_label, 2, 0, 1, 1)
        self.circular_maxVal = QtWidgets.QLabel(self.circularity_groupbox)
        self.circular_maxVal.setMaximumSize(QtCore.QSize(100, 16777215))
        self.circular_maxVal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.circular_maxVal.setAlignment(QtCore.Qt.AlignCenter)
        self.circular_maxVal.setObjectName("circular_maxVal")
        self.cicularity_groupbox_layout.addWidget(self.circular_maxVal, 2, 1, 1, 1)
        self.circular_maxVal_slider = QtWidgets.QSlider(self.circularity_groupbox)
        self.circular_maxVal_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.circular_maxVal_slider.setOrientation(QtCore.Qt.Horizontal)
        self.circular_maxVal_slider.setObjectName("circular_maxVal_slider")
        self.cicularity_groupbox_layout.addWidget(self.circular_maxVal_slider, 2, 2, 1, 1)
        self.circular_reset_btn = QtWidgets.QPushButton(self.circularity_groupbox)
        self.circular_reset_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.circular_reset_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.circular_reset_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.circular_reset_btn.setAutoFillBackground(False)
        self.circular_reset_btn.setCheckable(False)
        self.circular_reset_btn.setObjectName("circular_reset_btn")
        self.cicularity_groupbox_layout.addWidget(self.circular_reset_btn, 3, 2, 1, 1)
        self.ballDetection_tab_layout.addWidget(self.circularity_groupbox, 1, 0, 1, 1)
        self.area_groupbox = QtWidgets.QGroupBox(self.ballDetection_tab)
        self.area_groupbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.area_groupbox.setObjectName("area_groupbox")
        self.area_groupbox_layout = QtWidgets.QGridLayout(self.area_groupbox)
        self.area_groupbox_layout.setObjectName("area_groupbox_layout")
        self.area_filterBy_label = QtWidgets.QLabel(self.area_groupbox)
        self.area_filterBy_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.area_filterBy_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.area_filterBy_label.setAlignment(QtCore.Qt.AlignCenter)
        self.area_filterBy_label.setObjectName("area_filterBy_label")
        self.area_groupbox_layout.addWidget(self.area_filterBy_label, 0, 0, 1, 1)
        self.area_filterBy_yradio = QtWidgets.QRadioButton(self.area_groupbox)
        self.area_filterBy_yradio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.area_filterBy_yradio.setObjectName("area_filterBy_yradio")
        self.area_groupbox_layout.addWidget(self.area_filterBy_yradio, 0, 1, 1, 1)
        self.area_filterBy_nradio = QtWidgets.QRadioButton(self.area_groupbox)
        self.area_filterBy_nradio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.area_filterBy_nradio.setObjectName("area_filterBy_nradio")
        self.area_groupbox_layout.addWidget(self.area_filterBy_nradio, 0, 2, 1, 1)
        self.area_minVal_label = QtWidgets.QLabel(self.area_groupbox)
        self.area_minVal_label.setMaximumSize(QtCore.QSize(300, 16777215))
        self.area_minVal_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.area_minVal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.area_minVal_label.setObjectName("area_minVal_label")
        self.area_groupbox_layout.addWidget(self.area_minVal_label, 1, 0, 1, 1)
        self.area_minVal = QtWidgets.QLabel(self.area_groupbox)
        self.area_minVal.setMaximumSize(QtCore.QSize(100, 16777215))
        self.area_minVal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.area_minVal.setAlignment(QtCore.Qt.AlignCenter)
        self.area_minVal.setObjectName("area_minVal")
        self.area_groupbox_layout.addWidget(self.area_minVal, 1, 1, 1, 1)
        self.area_minVal_slider = QtWidgets.QSlider(self.area_groupbox)
        self.area_minVal_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.area_minVal_slider.setOrientation(QtCore.Qt.Horizontal)
        self.area_minVal_slider.setObjectName("area_minVal_slider")
        self.area_groupbox_layout.addWidget(self.area_minVal_slider, 1, 2, 1, 1)
        self.area_maxVal_label = QtWidgets.QLabel(self.area_groupbox)
        self.area_maxVal_label.setMaximumSize(QtCore.QSize(300, 16777215))
        self.area_maxVal_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.area_maxVal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.area_maxVal_label.setObjectName("area_maxVal_label")
        self.area_groupbox_layout.addWidget(self.area_maxVal_label, 2, 0, 1, 1)
        self.area_maxVal = QtWidgets.QLabel(self.area_groupbox)
        self.area_maxVal.setMaximumSize(QtCore.QSize(100, 16777215))
        self.area_maxVal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.area_maxVal.setAlignment(QtCore.Qt.AlignCenter)
        self.area_maxVal.setObjectName("area_maxVal")
        self.area_groupbox_layout.addWidget(self.area_maxVal, 2, 1, 1, 1)
        self.area_maxVal_slider = QtWidgets.QSlider(self.area_groupbox)
        self.area_maxVal_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.area_maxVal_slider.setOrientation(QtCore.Qt.Horizontal)
        self.area_maxVal_slider.setObjectName("area_maxVal_slider")
        self.area_groupbox_layout.addWidget(self.area_maxVal_slider, 2, 2, 1, 1)
        self.area_reset_btn = QtWidgets.QPushButton(self.area_groupbox)
        self.area_reset_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.area_reset_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.area_reset_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.area_reset_btn.setAutoFillBackground(False)
        self.area_reset_btn.setCheckable(False)
        self.area_reset_btn.setObjectName("area_reset_btn")
        self.area_groupbox_layout.addWidget(self.area_reset_btn, 3, 2, 1, 1)
        self.ballDetection_tab_layout.addWidget(self.area_groupbox, 1, 1, 1, 1)
        self.settings_tabs.addTab(self.ballDetection_tab, "")
        self.settings_groupbox_layout.addWidget(self.settings_tabs)
        self.central_widget_layout.addWidget(self.settings_groupbox, 0, 0, 1, 1)
        self.videoPlayer_groupbox = QtWidgets.QGroupBox(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoPlayer_groupbox.sizePolicy().hasHeightForWidth())
        self.videoPlayer_groupbox.setSizePolicy(sizePolicy)
        self.videoPlayer_groupbox.setMinimumSize(QtCore.QSize(0, 0))
        self.videoPlayer_groupbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.videoPlayer_groupbox.setObjectName("videoPlayer_groupbox")
        self.videoPlayer_groupbox_layout = QtWidgets.QGridLayout(self.videoPlayer_groupbox)
        self.videoPlayer_groupbox_layout.setContentsMargins(15, 15, 15, 15)
        self.videoPlayer_groupbox_layout.setObjectName("videoPlayer_groupbox_layout")
        self.videoPlayer_widget = QtWidgets.QWidget(self.videoPlayer_groupbox)
        self.videoPlayer_widget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.videoPlayer_widget.setObjectName("videoPlayer_widget")
        self.videoPlayer_widget_layout = QtWidgets.QHBoxLayout(self.videoPlayer_widget)
        self.videoPlayer_widget_layout.setObjectName("videoPlayer_widget_layout")
        self.videoPlayer_options_layout = QtWidgets.QGridLayout()
        self.videoPlayer_options_layout.setHorizontalSpacing(10)
        self.videoPlayer_options_layout.setObjectName("videoPlayer_options_layout")
        self.play_btn = QtWidgets.QPushButton(self.videoPlayer_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_btn.sizePolicy().hasHeightForWidth())
        self.play_btn.setSizePolicy(sizePolicy)
        self.play_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.play_btn.setBaseSize(QtCore.QSize(0, 0))
        self.play_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.play_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.play_btn.setAutoDefault(False)
        self.play_btn.setFlat(False)
        self.play_btn.setObjectName("play_btn")
        self.videoPlayer_options_layout.addWidget(self.play_btn, 0, 3, 1, 1)
        self.restart_btn = QtWidgets.QPushButton(self.videoPlayer_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restart_btn.sizePolicy().hasHeightForWidth())
        self.restart_btn.setSizePolicy(sizePolicy)
        self.restart_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.restart_btn.setBaseSize(QtCore.QSize(0, 0))
        self.restart_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.restart_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.restart_btn.setAutoDefault(False)
        self.restart_btn.setFlat(False)
        self.restart_btn.setObjectName("restart_btn")
        self.videoPlayer_options_layout.addWidget(self.restart_btn, 1, 3, 1, 1)
        self.cropFrames_label = QtWidgets.QLabel(self.videoPlayer_widget)
        self.cropFrames_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cropFrames_label.setIndent(5)
        self.cropFrames_label.setObjectName("cropFrames_label")
        self.videoPlayer_options_layout.addWidget(self.cropFrames_label, 1, 2, 1, 1)
        self.detectTable_btn = QtWidgets.QPushButton(self.videoPlayer_widget)
        self.detectTable_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detectTable_btn.sizePolicy().hasHeightForWidth())
        self.detectTable_btn.setSizePolicy(sizePolicy)
        self.detectTable_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.detectTable_btn.setBaseSize(QtCore.QSize(0, 0))
        self.detectTable_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.detectTable_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.detectTable_btn.setDefault(False)
        self.detectTable_btn.setFlat(False)
        self.detectTable_btn.setObjectName("detectTable_btn")
        self.videoPlayer_options_layout.addWidget(self.detectTable_btn, 2, 3, 1, 1)
        self.showThreshold_yradio = QtWidgets.QRadioButton(self.videoPlayer_widget)
        self.showThreshold_yradio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.showThreshold_yradio.setObjectName("showThreshold_yradio")
        self.videoPlayer_options_layout.addWidget(self.showThreshold_yradio, 0, 1, 1, 1)
        self.showThreshold_label = QtWidgets.QLabel(self.videoPlayer_widget)
        self.showThreshold_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.showThreshold_label.setIndent(5)
        self.showThreshold_label.setObjectName("showThreshold_label")
        self.videoPlayer_options_layout.addWidget(self.showThreshold_label, 0, 2, 1, 1)
        self.showThreshold_nradio = QtWidgets.QRadioButton(self.videoPlayer_widget)
        self.showThreshold_nradio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.showThreshold_nradio.setObjectName("showThreshold_nradio")
        self.videoPlayer_options_layout.addWidget(self.showThreshold_nradio, 0, 0, 1, 1)
        self.cropFrames_yradio = QtWidgets.QRadioButton(self.videoPlayer_widget)
        self.cropFrames_yradio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cropFrames_yradio.setObjectName("cropFrames_yradio")
        self.videoPlayer_options_layout.addWidget(self.cropFrames_yradio, 1, 1, 1, 1)
        self.cropFrames_nradio = QtWidgets.QRadioButton(self.videoPlayer_widget)
        self.cropFrames_nradio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cropFrames_nradio.setObjectName("cropFrames_nradio")
        self.videoPlayer_options_layout.addWidget(self.cropFrames_nradio, 1, 0, 1, 1)
        self.videoPlayer_widget_layout.addLayout(self.videoPlayer_options_layout)
        self.videoPlayer_groupbox_layout.addWidget(self.videoPlayer_widget, 1, 0, 1, 1)
        self.videoPlayer_videoFrame = QtWidgets.QFrame(self.videoPlayer_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoPlayer_videoFrame.sizePolicy().hasHeightForWidth())
        self.videoPlayer_videoFrame.setSizePolicy(sizePolicy)
        self.videoPlayer_videoFrame.setMaximumSize(QtCore.QSize(800, 16777215))
        self.videoPlayer_videoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.videoPlayer_videoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.videoPlayer_videoFrame.setObjectName("videoPlayer_videoFrame")
        self.videoPlayer_videoFrame_layout = QtWidgets.QHBoxLayout(self.videoPlayer_videoFrame)
        self.videoPlayer_videoFrame_layout.setContentsMargins(15, 15, 15, 15)
        self.videoPlayer_videoFrame_layout.setSpacing(6)
        self.videoPlayer_videoFrame_layout.setObjectName("videoPlayer_videoFrame_layout")
        self.selectVideoFile_btn = QtWidgets.QPushButton(self.videoPlayer_videoFrame)
        self.selectVideoFile_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.selectVideoFile_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.selectVideoFile_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selectVideoFile_btn.setObjectName("selectVideoFile_btn")
        self.videoPlayer_videoFrame_layout.addWidget(self.selectVideoFile_btn)
        self.videoPlayer_groupbox_layout.addWidget(self.videoPlayer_videoFrame, 0, 0, 1, 1)
        self.central_widget_layout.addWidget(self.videoPlayer_groupbox, 0, 1, 2, 1)
        self.logging_groupbox = QtWidgets.QGroupBox(self.central_widget)
        self.logging_groupbox.setFlat(False)
        self.logging_groupbox.setObjectName("logging_groupbox")
        self.logging_groupbox_layout = QtWidgets.QHBoxLayout(self.logging_groupbox)
        self.logging_groupbox_layout.setContentsMargins(15, 15, 15, 15)
        self.logging_groupbox_layout.setSpacing(15)
        self.logging_groupbox_layout.setObjectName("logging_groupbox_layout")
        self.logging_widget = QtWidgets.QWidget(self.logging_groupbox)
        self.logging_widget.setMaximumSize(QtCore.QSize(567, 16777215))
        self.logging_widget.setObjectName("logging_widget")
        self.logging_widget_layout = QtWidgets.QHBoxLayout(self.logging_widget)
        self.logging_widget_layout.setContentsMargins(0, 0, 0, 0)
        self.logging_widget_layout.setSpacing(15)
        self.logging_widget_layout.setObjectName("logging_widget_layout")
        self.ballsPotted_layout = QtWidgets.QVBoxLayout()
        self.ballsPotted_layout.setSpacing(10)
        self.ballsPotted_layout.setObjectName("ballsPotted_layout")
        self.ballsPotted_label = QtWidgets.QLabel(self.logging_widget)
        self.ballsPotted_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ballsPotted_label.setObjectName("ballsPotted_label")
        self.ballsPotted_layout.addWidget(self.ballsPotted_label)
        self.ballsPotted_list = QtWidgets.QListWidget(self.logging_widget)
        self.ballsPotted_list.setObjectName("ballsPotted_list")
        self.ballsPotted_layout.addWidget(self.ballsPotted_list)
        self.logging_widget_layout.addLayout(self.ballsPotted_layout)
        self.snapshot_layout = QtWidgets.QGridLayout()
        self.snapshot_layout.setHorizontalSpacing(10)
        self.snapshot_layout.setVerticalSpacing(5)
        self.snapshot_layout.setObjectName("snapshot_layout")
        self.lastShot_brownsCount = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lastShot_brownsCount.setFont(font)
        self.lastShot_brownsCount.setAlignment(QtCore.Qt.AlignCenter)
        self.lastShot_brownsCount.setObjectName("lastShot_brownsCount")
        self.snapshot_layout.addWidget(self.lastShot_brownsCount, 7, 1, 1, 1)
        self.whites_label = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.whites_label.setFont(font)
        self.whites_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.whites_label.setObjectName("whites_label")
        self.snapshot_layout.addWidget(self.whites_label, 3, 0, 1, 1)
        self.snapshot_horz_line2 = QtWidgets.QFrame(self.logging_widget)
        self.snapshot_horz_line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.snapshot_horz_line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.snapshot_horz_line2.setObjectName("snapshot_horz_line2")
        self.snapshot_layout.addWidget(self.snapshot_horz_line2, 11, 0, 1, 3)
        self.lastShotCount_label = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lastShotCount_label.setFont(font)
        self.lastShotCount_label.setAlignment(QtCore.Qt.AlignCenter)
        self.lastShotCount_label.setObjectName("lastShotCount_label")
        self.snapshot_layout.addWidget(self.lastShotCount_label, 2, 1, 1, 1)
        self.curBallCount_brownsCount = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.curBallCount_brownsCount.setFont(font)
        self.curBallCount_brownsCount.setAlignment(QtCore.Qt.AlignCenter)
        self.curBallCount_brownsCount.setObjectName("curBallCount_brownsCount")
        self.snapshot_layout.addWidget(self.curBallCount_brownsCount, 7, 2, 1, 1)
        self.lastShot_bluesCount = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lastShot_bluesCount.setFont(font)
        self.lastShot_bluesCount.setAlignment(QtCore.Qt.AlignCenter)
        self.lastShot_bluesCount.setObjectName("lastShot_bluesCount")
        self.snapshot_layout.addWidget(self.lastShot_bluesCount, 8, 1, 1, 1)
        self.reds_label = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.reds_label.setFont(font)
        self.reds_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.reds_label.setObjectName("reds_label")
        self.snapshot_layout.addWidget(self.reds_label, 4, 0, 1, 1)
        self.yellows_labels = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.yellows_labels.setFont(font)
        self.yellows_labels.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yellows_labels.setObjectName("yellows_labels")
        self.snapshot_layout.addWidget(self.yellows_labels, 5, 0, 1, 1)
        self.lastShot_blacksCount = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lastShot_blacksCount.setFont(font)
        self.lastShot_blacksCount.setAlignment(QtCore.Qt.AlignCenter)
        self.lastShot_blacksCount.setObjectName("lastShot_blacksCount")
        self.snapshot_layout.addWidget(self.lastShot_blacksCount, 10, 1, 1, 1)
        self.blacks_label = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.blacks_label.setFont(font)
        self.blacks_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.blacks_label.setObjectName("blacks_label")
        self.snapshot_layout.addWidget(self.blacks_label, 10, 0, 1, 1)
        self.curBallCount_yellowsCount = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.curBallCount_yellowsCount.setFont(font)
        self.curBallCount_yellowsCount.setAlignment(QtCore.Qt.AlignCenter)
        self.curBallCount_yellowsCount.setObjectName("curBallCount_yellowsCount")
        self.snapshot_layout.addWidget(self.curBallCount_yellowsCount, 5, 2, 1, 1)
        self.lastShot_redsCount = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lastShot_redsCount.setFont(font)
        self.lastShot_redsCount.setAlignment(QtCore.Qt.AlignCenter)
        self.lastShot_redsCount.setObjectName("lastShot_redsCount")
        self.snapshot_layout.addWidget(self.lastShot_redsCount, 4, 1, 1, 1)
        self.pinks_label = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pinks_label.setFont(font)
        self.pinks_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pinks_label.setObjectName("pinks_label")
        self.snapshot_layout.addWidget(self.pinks_label, 9, 0, 1, 1)
        self.curBallCount_bluesCount = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.curBallCount_bluesCount.setFont(font)
        self.curBallCount_bluesCount.setAlignment(QtCore.Qt.AlignCenter)
        self.curBallCount_bluesCount.setObjectName("curBallCount_bluesCount")
        self.snapshot_layout.addWidget(self.curBallCount_bluesCount, 8, 2, 1, 1)
        self.curBallCount_greensCount = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.curBallCount_greensCount.setFont(font)
        self.curBallCount_greensCount.setAlignment(QtCore.Qt.AlignCenter)
        self.curBallCount_greensCount.setObjectName("curBallCount_greensCount")
        self.snapshot_layout.addWidget(self.curBallCount_greensCount, 6, 2, 1, 1)
        self.lastShot_pinksCount = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lastShot_pinksCount.setFont(font)
        self.lastShot_pinksCount.setAlignment(QtCore.Qt.AlignCenter)
        self.lastShot_pinksCount.setObjectName("lastShot_pinksCount")
        self.snapshot_layout.addWidget(self.lastShot_pinksCount, 9, 1, 1, 1)
        self.curBallCount_redsCount = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.curBallCount_redsCount.setFont(font)
        self.curBallCount_redsCount.setAlignment(QtCore.Qt.AlignCenter)
        self.curBallCount_redsCount.setObjectName("curBallCount_redsCount")
        self.snapshot_layout.addWidget(self.curBallCount_redsCount, 4, 2, 1, 1)
        self.lastShot_whitesCount = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lastShot_whitesCount.setFont(font)
        self.lastShot_whitesCount.setAlignment(QtCore.Qt.AlignCenter)
        self.lastShot_whitesCount.setObjectName("lastShot_whitesCount")
        self.snapshot_layout.addWidget(self.lastShot_whitesCount, 3, 1, 1, 1)
        self.curBallCount_whitesCount = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.curBallCount_whitesCount.setFont(font)
        self.curBallCount_whitesCount.setAlignment(QtCore.Qt.AlignCenter)
        self.curBallCount_whitesCount.setObjectName("curBallCount_whitesCount")
        self.snapshot_layout.addWidget(self.curBallCount_whitesCount, 3, 2, 1, 1)
        self.curBallCount_label = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.curBallCount_label.setFont(font)
        self.curBallCount_label.setAlignment(QtCore.Qt.AlignCenter)
        self.curBallCount_label.setObjectName("curBallCount_label")
        self.snapshot_layout.addWidget(self.curBallCount_label, 2, 2, 1, 1)
        self.blues_label = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.blues_label.setFont(font)
        self.blues_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.blues_label.setObjectName("blues_label")
        self.snapshot_layout.addWidget(self.blues_label, 8, 0, 1, 1)
        self.lastShot_yellowsCount = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lastShot_yellowsCount.setFont(font)
        self.lastShot_yellowsCount.setAlignment(QtCore.Qt.AlignCenter)
        self.lastShot_yellowsCount.setObjectName("lastShot_yellowsCount")
        self.snapshot_layout.addWidget(self.lastShot_yellowsCount, 5, 1, 1, 1)
        self.curBallCount_pinksCount = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.curBallCount_pinksCount.setFont(font)
        self.curBallCount_pinksCount.setAlignment(QtCore.Qt.AlignCenter)
        self.curBallCount_pinksCount.setObjectName("curBallCount_pinksCount")
        self.snapshot_layout.addWidget(self.curBallCount_pinksCount, 9, 2, 1, 1)
        self.whiteStatus_label = QtWidgets.QLabel(self.logging_widget)
        self.whiteStatus_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.whiteStatus_label.setObjectName("whiteStatus_label")
        self.snapshot_layout.addWidget(self.whiteStatus_label, 0, 0, 1, 2)
        self.browns_label = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.browns_label.setFont(font)
        self.browns_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.browns_label.setObjectName("browns_label")
        self.snapshot_layout.addWidget(self.browns_label, 7, 0, 1, 1)
        self.greens_label = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.greens_label.setFont(font)
        self.greens_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.greens_label.setObjectName("greens_label")
        self.snapshot_layout.addWidget(self.greens_label, 6, 0, 1, 1)
        self.curBallCount_blacksCount = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.curBallCount_blacksCount.setFont(font)
        self.curBallCount_blacksCount.setAlignment(QtCore.Qt.AlignCenter)
        self.curBallCount_blacksCount.setObjectName("curBallCount_blacksCount")
        self.snapshot_layout.addWidget(self.curBallCount_blacksCount, 10, 2, 1, 1)
        self.whiteStatus = QtWidgets.QLabel(self.logging_widget)
        self.whiteStatus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.whiteStatus.setObjectName("whiteStatus")
        self.snapshot_layout.addWidget(self.whiteStatus, 0, 2, 1, 1)
        self.lastShot_greensCount = QtWidgets.QLabel(self.logging_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lastShot_greensCount.setFont(font)
        self.lastShot_greensCount.setAlignment(QtCore.Qt.AlignCenter)
        self.lastShot_greensCount.setObjectName("lastShot_greensCount")
        self.snapshot_layout.addWidget(self.lastShot_greensCount, 6, 1, 1, 1)
        self.snapshot_horz_line1 = QtWidgets.QFrame(self.logging_widget)
        self.snapshot_horz_line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.snapshot_horz_line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.snapshot_horz_line1.setObjectName("snapshot_horz_line1")
        self.snapshot_layout.addWidget(self.snapshot_horz_line1, 1, 0, 1, 3)
        self.logging_widget_layout.addLayout(self.snapshot_layout)
        self.logging_widget_layout.setStretch(0, 2)
        self.logging_widget_layout.setStretch(1, 1)
        self.logging_groupbox_layout.addWidget(self.logging_widget)
        self.central_widget_layout.addWidget(self.logging_groupbox, 1, 0, 1, 1)
        self.central_widget_layout.setColumnStretch(0, 3)
        self.central_widget_layout.setColumnStretch(1, 5)
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1269, 22))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        self.menuExit_2 = QtWidgets.QMenu(self.menubar)
        self.menuExit_2.setObjectName("menuExit_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setEnabled(True)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSelect_Video_File = QtWidgets.QAction(MainWindow)
        self.actionSelect_Video_File.setObjectName("actionSelect_Video_File")
        self.menuSettings.addAction(self.actionLoad)
        self.menuSettings.addAction(self.actionSave)
        self.menuExit.addAction(self.actionSelect_Video_File)
        self.menubar.addAction(self.menuExit.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuExit_2.menuAction())

        self.retranslateUi(MainWindow)
        self.settings_tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.settings_groupbox.setTitle(_translate("MainWindow", "Settings"))
        self.detectColour_label.setText(_translate("MainWindow", "Detect Colour"))
        self.showMask_label.setText(_translate("MainWindow", "Show Mask"))
        self.showMask_yradio.setText(_translate("MainWindow", "Yes"))
        self.showMask_nradio.setText(_translate("MainWindow", "No"))
        self.reset_btn.setText(_translate("MainWindow", "Reset"))
        self.lRange_label.setText(_translate("MainWindow", "Lower Range"))
        self.uRange_label.setText(_translate("MainWindow", "Upper Range"))
        self.hue_label.setText(_translate("MainWindow", "Hue"))
        self.lHue_label.setText(_translate("MainWindow", "0"))
        self.uHue_label.setText(_translate("MainWindow", "0"))
        self.sat_label.setText(_translate("MainWindow", "Saturation"))
        self.lSat_label.setText(_translate("MainWindow", "0"))
        self.uSat_label.setText(_translate("MainWindow", "0"))
        self.val_label.setText(_translate("MainWindow", "Value"))
        self.lVal_label.setText(_translate("MainWindow", "0"))
        self.uVal_label.setText(_translate("MainWindow", "0"))
        self.settings_tabs.setTabText(self.settings_tabs.indexOf(self.colourDetection_tab), _translate("MainWindow", "Colour Detection"))
        self.convexity_groupbox.setTitle(_translate("MainWindow", "Convexity"))
        self.convexity_filterBy_label.setText(_translate("MainWindow", "Filter By"))
        self.convexity_filterBy_yradio.setText(_translate("MainWindow", "Yes"))
        self.convexity_filterBy_nradio.setText(_translate("MainWindow", "No"))
        self.convexity_minVal_label.setText(_translate("MainWindow", "Minimum Value"))
        self.convexity_minVal.setText(_translate("MainWindow", "0"))
        self.convexity_maxVal_label.setText(_translate("MainWindow", "Maximum Value"))
        self.convexity_maxVal.setText(_translate("MainWindow", "0"))
        self.convexity_reset_btn.setText(_translate("MainWindow", "Reset"))
        self.inertia_groupbox.setTitle(_translate("MainWindow", "Inertia"))
        self.inertia_filterBy_label.setText(_translate("MainWindow", "Filter By"))
        self.inertia_filterBy_yradio.setText(_translate("MainWindow", "Yes"))
        self.inertia_filterBy_nradio.setText(_translate("MainWindow", "No"))
        self.inertia_minVal_label.setText(_translate("MainWindow", "Minimum Value"))
        self.inertia_minVal.setText(_translate("MainWindow", "0"))
        self.inertia_maxVal_label.setText(_translate("MainWindow", "Maximum Value"))
        self.inertia_maxVal.setText(_translate("MainWindow", "0"))
        self.inertia_reset_btn.setText(_translate("MainWindow", "Reset"))
        self.circularity_groupbox.setTitle(_translate("MainWindow", "Circularity"))
        self.circular_filterBy_label.setText(_translate("MainWindow", "Filter By"))
        self.circular_filterBy_yradio.setText(_translate("MainWindow", "Yes"))
        self.circular_filterBy_nradio.setText(_translate("MainWindow", "No"))
        self.circular_minVal_label.setText(_translate("MainWindow", "Minimum Value"))
        self.circular_minVal.setText(_translate("MainWindow", "0"))
        self.circular_maxVal_label.setText(_translate("MainWindow", "Maximum Value"))
        self.circular_maxVal.setText(_translate("MainWindow", "0"))
        self.circular_reset_btn.setText(_translate("MainWindow", "Reset"))
        self.area_groupbox.setTitle(_translate("MainWindow", "Area"))
        self.area_filterBy_label.setText(_translate("MainWindow", "Filter By"))
        self.area_filterBy_yradio.setText(_translate("MainWindow", "Yes"))
        self.area_filterBy_nradio.setText(_translate("MainWindow", "No"))
        self.area_minVal_label.setText(_translate("MainWindow", "Minimum Value"))
        self.area_minVal.setText(_translate("MainWindow", "0"))
        self.area_maxVal_label.setText(_translate("MainWindow", "Maximum Value"))
        self.area_maxVal.setText(_translate("MainWindow", "0"))
        self.area_reset_btn.setText(_translate("MainWindow", "Reset"))
        self.settings_tabs.setTabText(self.settings_tabs.indexOf(self.ballDetection_tab), _translate("MainWindow", "Ball Detection"))
        self.videoPlayer_groupbox.setTitle(_translate("MainWindow", "Video Player"))
        self.play_btn.setText(_translate("MainWindow", "Play"))
        self.restart_btn.setText(_translate("MainWindow", "Restart"))
        self.cropFrames_label.setText(_translate("MainWindow", "Crop Frames"))
        self.detectTable_btn.setText(_translate("MainWindow", "Detect Table"))
        self.showThreshold_yradio.setText(_translate("MainWindow", "Yes"))
        self.showThreshold_label.setText(_translate("MainWindow", "Show Threshold"))
        self.showThreshold_nradio.setText(_translate("MainWindow", "No"))
        self.cropFrames_yradio.setText(_translate("MainWindow", "Yes"))
        self.cropFrames_nradio.setText(_translate("MainWindow", "No"))
        self.selectVideoFile_btn.setText(_translate("MainWindow", "Select Video File"))
        self.logging_groupbox.setTitle(_translate("MainWindow", "Logging"))
        self.ballsPotted_label.setText(_translate("MainWindow", "Balls Potted"))
        self.lastShot_brownsCount.setText(_translate("MainWindow", "0"))
        self.whites_label.setText(_translate("MainWindow", "Whites"))
        self.lastShotCount_label.setText(_translate("MainWindow", "Last Shot Ball Count"))
        self.curBallCount_brownsCount.setText(_translate("MainWindow", "0"))
        self.lastShot_bluesCount.setText(_translate("MainWindow", "0"))
        self.reds_label.setText(_translate("MainWindow", "Reds"))
        self.yellows_labels.setText(_translate("MainWindow", "Yellows"))
        self.lastShot_blacksCount.setText(_translate("MainWindow", "0"))
        self.blacks_label.setText(_translate("MainWindow", "Blacks"))
        self.curBallCount_yellowsCount.setText(_translate("MainWindow", "0"))
        self.lastShot_redsCount.setText(_translate("MainWindow", "0"))
        self.pinks_label.setText(_translate("MainWindow", "Pinks"))
        self.curBallCount_bluesCount.setText(_translate("MainWindow", "0"))
        self.curBallCount_greensCount.setText(_translate("MainWindow", "0"))
        self.lastShot_pinksCount.setText(_translate("MainWindow", "0"))
        self.curBallCount_redsCount.setText(_translate("MainWindow", "0"))
        self.lastShot_whitesCount.setText(_translate("MainWindow", "0"))
        self.curBallCount_whitesCount.setText(_translate("MainWindow", "0"))
        self.curBallCount_label.setText(_translate("MainWindow", "Current Ball Count"))
        self.blues_label.setText(_translate("MainWindow", "Blues"))
        self.lastShot_yellowsCount.setText(_translate("MainWindow", "0"))
        self.curBallCount_pinksCount.setText(_translate("MainWindow", "0"))
        self.whiteStatus_label.setText(_translate("MainWindow", "White Ball Status"))
        self.browns_label.setText(_translate("MainWindow", "Browns"))
        self.greens_label.setText(_translate("MainWindow", "Greens"))
        self.curBallCount_blacksCount.setText(_translate("MainWindow", "0"))
        self.whiteStatus.setText(_translate("MainWindow", "stopped..."))
        self.lastShot_greensCount.setText(_translate("MainWindow", "0"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuExit.setTitle(_translate("MainWindow", "File"))
        self.menuExit_2.setTitle(_translate("MainWindow", "Exit"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSelect_Video_File.setText(_translate("MainWindow", "Select Video File"))
